import palette from "./palette";

export default {
  h1: {
    fontWeight: 400,
    fontSize: "48px",
    letterSpacing: "0px",
    lineHeight: "64px",
  },
  h2: {
    color: palette.text_colors.primary_550,
    fontWeight: 500,
    fontSize: "32px",
    letterSpacing: "-0.24px",
    lineHeight: "40px",
  },
  h3: {
    color: palette.text.primary,
    fontWeight: 500,
    fontSize: "24px",
    letterSpacing: "-0.06px",
    lineHeight: "28px",
  },
  h4: {
    color: palette.text.primary,
    fontWeight: 500,
    fontSize: "20px",
    lineHeight: "24px",
  },
  h5: {
    color: palette.text_colors.neutral_675,
    fontStyle: "normal",
    fontSize: "18px",
    fontWeight: 500,
    lineHeight: "24px",
  },
  h6: {
    color: palette.text_colors.primary_550,
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "16px",
    // letterSpacing: "-0.05px",
    lineHeight: "20px",
  },
  subtitle1: {
    color: palette.text_colors.neutral_675,
    fontWeight: 500,
    fontSize: "14px",
    lineHeight: "20px",
  },
  subtitle2: {
    fontWeight: 400,
    fontSize: "12px",
    fontStyle: "normal",
    lineHeight: "20px",
  },
  body1: {
    color: palette.text_colors.neutral_675,
    fontWeight: 400,
    fontStyle: "normal",
    fontSize: "16px",
    lineHeight: "20px",
  },
  body2: {
    color: palette.text_colors.neutral_675,
    fontWeight: 400,
    fontStyle: "normal",
    fontSize: "14px",
    lineHeight: "16px",
  },
  button: {
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "12px",
    lineHeight: "16px",
    textTransform: "none",
  },
  caption: {
    fontWeight: 600,
    fontStyle: "normal",
    fontSize: "14px",
    lineHeight: "17px",
  },
  overline: {
    fontSize: "10px",
    letterSpacing: "0px",
    lineHeight: "16px",
    fontStyle: "normal",
    textTransform: "none",
  },
};
